### ISSUE TITLE
Feature Request: Add Service for Hand/GPIO State Control

### ISSUE THREAD

**Issue by tjeerdvandijk** [Mitsubishi-Electric-Asia/melfa_ros2_driver#11]
**Problem:**

Currently, the hand/GPIO state can only be controlled through a ROS topic, which has some limitations. Specifically:

1. **Lack of Confirmation:** When publishing a command to change the hand/GPIO state, there is no built-in mechanism to confirm that the command was successfully received and acted upon. This is an inherent limitation of ROS topics, even with optimal QoS settings. In contrast, ROS services will return a confirmation, allowing the caller to know whether the command was successfully processed.

2. **Safety Concerns:** The lack of confirmation has its risks. For example, if the gripper is not confirmed to be in the desired state, it may attempt to pick up an object while closed, which could result in hardware damage.

**Proposed Solution:**

To give developers more flexibility and ensure safer operation, I suggest adding a service for changing the hand/GPIO state in addition to the existing topic. This would allow developers to choose the most suitable method based on their requirements.

**Comment by offinliu** [comment]
Hi @tjeerdvandijk,

This function exist. 
Refer to https://github.com/Mitsubishi-Electric-Asia/melfa_ros2_driver/blob/humble/doc/melfa_ros2_driver.md, __Example 4.2__.
You can use the service to write directly. However, there are some limitations to ROS services.

There are two ways to implement this depending on the type of gripper.
### 1. gripper with no return input
- MELFA Hand I/O is not limited to output:900. input:900 is commonly used as a gripper state return input. However, not all grippers have this function. Such grippers are open loop.
- I would recommend using the topic to write to hand_io and use the service to monitor address output:900 with "READ_OUT". This will allow the flexibility of ROS2 topics especially in OOP nodes.
- logic: MELFA ROS2 sends a packet with __1. a write command to output:900__, __2. a request to read data at output:900__.
- logic: MELFA robot controller receives this packet, modifies output:900, reads output:900 after it is written and sends a packet with the latest state of output:900. All done within 1 control cycle which is 3.5ms. If CR800-Q is used, it's 7.11ms.
- you can find this implementation in https://github.com/Mitsubishi-Electric-Asia/melfa_ros2_masterclass_2024/blob/main/melfa_rv5as_masterclass/src/plc_.cpp, 
- line 101 void gripper_state_callback(const melfa_msgs::msg::GpioState& msg) monitors the hand states.
- line 163 void gripper_command_callback(const melfa_masterclass_msgs::msg::GripperState& msg) writes to MELFA hand_io.

### 2. gripper with return input
- in this case, you will read from input:900 using "READ_IN".
- the logic is the same but the reply packet sends the state of input:900 instead. 

Only no.2 ensures a close loop control on MELFA gripper.

Please let me know if this helps.

**Comment by offinliu** [comment]
do note that output:900 does not take into account the time taken for the gripper to close completely. This function is implemented by the gripper OEM by utilizing input:900. If the gripper OEM does not use input:900 or any other signal to indicate gripper states, then there is no way for MELFA to read the state of the open loop gripper. One can only set a delay and assume that the gripper has reached the intended state.

**Comment by tjeerdvandijk** [comment]
Thanks for the clarification, My apologies—I hadn't realized this, despite spending quite a bit of time analyzing the masterclass code. I'll take a closer look at your reply and the code after the weekend

**Comment by tjeerdvandijk** [comment]
Hello @offinliu ,

I was able to get the service working and monitor the gripper, which turned out to be relatively straightforward based on your explanation.

Since all the necessary features for closed-loop control are already in place, it seems logical to me to incorporate a ROS action into the driver. Based on your description, this functionality currently has to reside within our own package, but I believe it would be more beneficial if it were integrated directly into the driver as an action.

Your comment provides all the necessary details for implementing this feature. However, I am unsure if this can be structured in a useful way, given the variation hardware control, which is code of the driver i'm not very familiar with. If this is not feasible, I believe the issue can be closed.

**Comment by offinliu** [comment]
Hi @tjeerdvandijk ,

Thank you for the reply.

I do not think there is a need for a ROS action. The IO controllers use the ros2_control command and state interfaces which is, in my opinion, more robust than pub/sub. 

Here's how the melfa io controller works:
Input from application (service or topic)
|-> Input is processed and modifies the ros2_control gpio command interface
|-> the command interface sends the command at a fix frequency. By default, with 7 interfaces, it is 41+Hz. 

receive a reply from MELFA robot controller
|->data is assigned to the io state interface which is subscribed by the user application to monitor io state
|-> updated at the same frequency as the command interface

When you publish to the topic, the published data is processed by the gpio controller. There is no need an action service. In fact, it wouldn't contribute to performance, and it may have slower response compared to the method I suggested in the earlier reply.

If you require extremely fast IO, I suggest using our MELSEC PLC's high speed I/O module to interface with your peripheral hardware, write a simple PLC program which can operate in microseconds to process the data and map it to your robot controller shared I/O. 

For single robot configurations, I suggest the FX5U PLC. It comes with built-in analog and digital I/O and has a built-in 24VDC PSU for low-power peripheral devices such as sensors.
